### ISSUE TITLE
Customized Configuration

### ISSUE THREAD

**Issue by ivaquero** [Enter-tainer/typstyle#115]
It would be better to have a config file (such as `typstyle.toml`) to tweak style options. 

For example, someone wants to keep extra blank lines between paragraphs while others don't, then there can be an option to tweak

```toml
[content]
  extra-blank-lines = 1
[math]
  space-between-operators = 1
...
```
